name: SpacesNavigationDemoApp
options:
  minimumXcodeGenVersion: 2.38.0
packages:
  SpacesNavigation:
    path: ..
targets:
  SpacesNavigationDemoApp:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.bri.SpacesNavigationDemoApp
        PRODUCT_NAME: SpacesNavigationDemoApp
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: YES
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: SpacesNavigation
        product: SpacesNavigation

